### PR TITLE
X25519 keys

### LINKED ISSUE #4: Naming problems regarding Curve 25519 in README and Code
Hello,

I noticed that the README mentions "Curve Ed25519", which according to D. J. Bernstein is wrong as the curve is Curve25519  [https://mailarchive.ietf.org/arch/msg/cfrg/-9LEdnzVrE5RORux3Oo_oDDRksU/]( https://mailarchive.ietf.org/arch/msg/cfrg/-9LEdnzVrE5RORux3Oo_oDDRksU/)
I think the README should be fixed accordingly to respect this naming convention.

Moreover, as you are doing a Diffie-Hellman Key Exchange, you are using X25519 keys (as in the name of the Dalek cryptography library) and not Ed25519, and the code should also be fixed accordingly.

Regards

### PR DESCRIPTION
**Pull request by sashaconway**
Add X25519 keys parsing capabilities and rename the keys parser package accordingly.

This should fix #4 .

### CODE REVIEW

File: curve25519_parser/src/lib.rs [hunk 1]
```diff
@@ -367,25 +380,25 @@ mod tests {
...
-        let pub_keys_pem = parse_openssl_ed25519_pubkeys_pem_many(PEM_PUB).unwrap();
+        let pub_keys_pem = parse_openssl_25519_pubkeys_pem_many(PEM_PUB).unwrap();
         assert_eq!(pub_keys_pem.len(), 1);
-        let pub_key_der = parse_openssl_ed25519_pubkey(DER_PUB).unwrap();
+        let pub_key_der = parse_openssl_25519_pubkey(ED_DER_PUB).unwrap();
         assert_eq!(pub_key_der.as_bytes().len(), 32);
         assert_eq!(pub_key_der.as_bytes(), pub_keys_pem[0].as_bytes());
 
-        let pub_keys_pem = parse_openssl_ed25519_pubkeys_pem_many(PEM_PUB_MANY).unwrap();
+        let pub_keys_pem = parse_openssl_25519_pubkeys_pem_many(PEM_PUB_MANY).unwrap();
```
Comment (commial) [inline curve25519_parser/src/lib.rs:401]: It would be nice to add one of the new x25519 key to the `PEM_PUB_MANY`, and assert it is correctly recovered.
It would ensure that `parse_openssl_25519_pubkeys_pem_many` is able to parse both x25519 and ed25519 keys.
